{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.8.jar",
          "url": "spring-boot-starter-tomcat-3.3.8.jar",
          "size": 4793,
          "sha512": "3a58963768867ef99a948cac3c23e411217a4c48c79cdf7c84f6263e353041ef82c3c3cfcc0131e037431826874e536f280cff1daa5c72dfc658c213e6c2c8c5",
          "sha256": "e03b90011972689aa44a961c5acf2073c7ef1e5d9c9d731e0cbd723f905d9d07",
          "sha1": "a978a7fe349094ae6adaf262092ea922a3b29568",
          "md5": "97482518ce01ad413e078eb403976f69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.8.jar",
          "url": "spring-boot-starter-tomcat-3.3.8.jar",
          "size": 4793,
          "sha512": "3a58963768867ef99a948cac3c23e411217a4c48c79cdf7c84f6263e353041ef82c3c3cfcc0131e037431826874e536f280cff1daa5c72dfc658c213e6c2c8c5",
          "sha256": "e03b90011972689aa44a961c5acf2073c7ef1e5d9c9d731e0cbd723f905d9d07",
          "sha1": "a978a7fe349094ae6adaf262092ea922a3b29568",
          "md5": "97482518ce01ad413e078eb403976f69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.8-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.3.8-javadoc.jar",
          "size": 4793,
          "sha512": "ada3a3cbe98ed4db29e2a076b86f9a46f918b6b0358d3842315e575b3b3789e58f1b58ed92b2a3336d27e10a3d9702b69e109221499394564cf1d6a6be594a24",
          "sha256": "9648599f2e952ed3d9e38aa98bbcab72b3e15d5f9004d30ee06373845f15a940",
          "sha1": "6bb02080d0435404bfcaa68c481dfa5a4ba0df53",
          "md5": "5b3336bfee7bb8534d6b0c259a1e4119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.8-sources.jar",
          "url": "spring-boot-starter-tomcat-3.3.8-sources.jar",
          "size": 4793,
          "sha512": "ada3a3cbe98ed4db29e2a076b86f9a46f918b6b0358d3842315e575b3b3789e58f1b58ed92b2a3336d27e10a3d9702b69e109221499394564cf1d6a6be594a24",
          "sha256": "9648599f2e952ed3d9e38aa98bbcab72b3e15d5f9004d30ee06373845f15a940",
          "sha1": "6bb02080d0435404bfcaa68c481dfa5a4ba0df53",
          "md5": "5b3336bfee7bb8534d6b0c259a1e4119"
        }
      ]
    }
  ]
}
