{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.5"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.3.8.jar",
          "url": "spring-boot-starter-test-3.3.8.jar",
          "size": 4791,
          "sha512": "7cba32b94b1243b0aa019f60b71785ce01976f73e7ceef330782b132017acafa67d515b0fc4141884070b6fe9f54fbd26716775f20fffca145cb6281f4f68f66",
          "sha256": "ce369d3c17a105c05241dad23a41f69475cf088d5fcfd8a65fa21cef41481271",
          "sha1": "374a17b90d08c9c88139930c4f5e419d674f2bdc",
          "md5": "2ca04dd6f97d8a0b86cdecadd980073b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.5"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.3.8.jar",
          "url": "spring-boot-starter-test-3.3.8.jar",
          "size": 4791,
          "sha512": "7cba32b94b1243b0aa019f60b71785ce01976f73e7ceef330782b132017acafa67d515b0fc4141884070b6fe9f54fbd26716775f20fffca145cb6281f4f68f66",
          "sha256": "ce369d3c17a105c05241dad23a41f69475cf088d5fcfd8a65fa21cef41481271",
          "sha1": "374a17b90d08c9c88139930c4f5e419d674f2bdc",
          "md5": "2ca04dd6f97d8a0b86cdecadd980073b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.3.8-javadoc.jar",
          "url": "spring-boot-starter-test-3.3.8-javadoc.jar",
          "size": 4791,
          "sha512": "b354867c062b8c66e4695919e51ffae497bbb1afc2a099a373c6ccab7e18d1c9b23a570acd501f1ef636bbd80ef32f9202c54fd50aab149a04ae6108d4dd1f04",
          "sha256": "191dfab94c3ae227354a5c38f352f5ee023a625ddda2c22b48e5ffbd8e16c82a",
          "sha1": "ce2be4c19f59fd5bdc443658e935b1f4acf542ec",
          "md5": "3416642d2488cb5b3e6792ad2e3b1346"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.3.8-sources.jar",
          "url": "spring-boot-starter-test-3.3.8-sources.jar",
          "size": 4791,
          "sha512": "b354867c062b8c66e4695919e51ffae497bbb1afc2a099a373c6ccab7e18d1c9b23a570acd501f1ef636bbd80ef32f9202c54fd50aab149a04ae6108d4dd1f04",
          "sha256": "191dfab94c3ae227354a5c38f352f5ee023a625ddda2c22b48e5ffbd8e16c82a",
          "sha1": "ce2be4c19f59fd5bdc443658e935b1f4acf542ec",
          "md5": "3416642d2488cb5b3e6792ad2e3b1346"
        }
      ]
    }
  ]
}
